apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 22i1269xx/worker:a959199a0c8b287c6828cd87ae620cf38c893df1
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: DATABASE_HOST
          value: "db"
